version: "3.8"

services:
  web:
    build:
      context: .
    command: daphne -b 0.0.0.0 -p 8000 wellence_project.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DB_NAME=task_db
      - DB_USER=postgres
      - DB_PASSWORD=Jjk123!*
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jjk123!*
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: