# Generated by Django 5.1.1 on 2024-09-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
