name: Docker Image CI

on:
  push:
    branches:
      - main
      - Azure
  pull_request:
    branches:
      - main
      - Azure

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag internship.azurecr.io/tasks_management_app:${{ github.sha }}
    
    - name: Push to ACR
      run: |
        docker login internship.azurecr.io -u internship -p ${{ secrets.ACR_PASSWORD }}
        docker push internship.azurecr.io/tasks_management_app:${{ github.sha }}
    
    - name: Deploy to Azure Container App 
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: internship
        containerAppName: ahmed
        resourceGroup: internship
        imageToDeploy: internship.azurecr.io/tasks_management_app:${{ github.sha }}
