name: Run Migrations

on:
    push:
        branches:
          - main
          - Azure
    pull_request:
        branches:
          - main
          - Azure

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Migrations
      run: |
        az containerapp revision run --name ahmed --resource-group internship --command "python manage.py migrate"